import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAIIND")
PINECONE_API_KEY = os.getenv("PINECONEIND")
SUPABASE_URL = os.getenv("SUPABASEURLIND")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASESERVICEKEYIND")
SUPABASE_API_KEY = os.getenv("SUPABASEAPIKEYIND")
FROM_EMAIL = os.getenv("FROMEMAILIND")
TO_EMAIL = os.getenv("TOEMAILIND1")
MAILERSEND_API_KEY = os.getenv("MAILERSENDAPIKEYIND")
FROM_NAME = os.getenv("FROMNAMEIND")
ROLLING_WINDOW_MIN = os.getenv("ROLLINGWINDOWMININD")
TEAMS_WEBHOOK_URL = os.getenv("TEAMSWEBHOOKURLIND")
TEAMS_WEBHOOK_URL_VAPI = os.getenv("TEAMSWEBHOOKURLVAPIIND")
VAPI_KEY = os.getenv("VAPIKEYIND")
ASSISTANT_ID = os.getenv("ASSISTANTIDIND")
PHONE_NUMBER_ID = os.getenv("PHONENUMBERIDIND")

REDIS_DB=os.getenv("REDIS_DB_IND")
REDIS_HOST=os.getenv("REDIS_HOST_IND")
REDIS_PORT=os.getenv("REDIS_PORT_IND")
REDIS_PASSWORD=os.getenv("REDIS_PASSWORD_IND")
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"