name: Build & Deploy – indrasol‑prd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write     # for azure/login OIDC

env:
  APP_NAME: indrasol-prd
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ─── BUILD (local) ───────────────────────────────────────────────────────────
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install deps
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r backend/requirements.txt

    # package only the backend folder
    - name: Zip site
      run: |
        cd backend                # <── change to your folder
        zip -r ../site.zip .
        cd ..

    - name: Upload artefact (for troubleshooting)
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: site.zip

    # ─── DEPLOY ─────────────────────────────────────────────────────────────────
    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id:      ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Web App
      id: deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name:   ${{ env.APP_NAME }}
        package:    site.zip             # <── a single ZIP file
